### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by JianbangZ** [artidoro/qlora#105]
Anyone else seeing this error when training?

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by nieallen** [comment]
Same error, did you solve it?

**Comment by mofalih64** [comment]
same here

**Comment by ag1988** [comment]
same error, were you able to solve it?

**Comment by ag1988** [comment]
I was getting the this error with `decapoda-research/llama-7b-hf` but the error went away using `huggyllama/llama-7b`.
