### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Godofnothing** [artidoro/qlora#124]
When attempting to run the script ./scripts/finetune_guanaco_7b.sh I face the following error on the beginning of training (after LoRA modules are added):
```bash
/opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [30,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**System specifications**:
NVIDIA RTX A6000
**Environment**:
python=3.10 with
```
pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
transformers           4.30.0.dev0
accelerate             0.20.0.dev0
bitsandbytes           0.39.0
datasets               2.12.0
```

**Comment by JianbangZ** [comment]
Other people found that the error went away using huggyllama/llama-7b instead of decapoda-research/llama-7b-hf. I don't know why
