### ISSUE TITLE
Is there a way to use data parallel training with qlora?

### ISSUE THREAD

**Issue by fomalhautb** [artidoro/qlora#177]
As mentioned in https://github.com/artidoro/qlora/issues/96#issuecomment-1571380953

> Hello I added some information on the multi-gpu setup in the README. In qlora.py we use Accelerate. You are correct that per_device_train/eval_batch_size refers to global batch size unlike the name suggests. Let me know if you still have questions.
> One thing to note is that accelerate does not use all GPUs optimally. It slices the model on different GPUs allowing training for models that don't fit on one GPU. However, at any given point in time during training, only one GPU will be in use at a time.

Also in the [Accelerate documents](https://huggingface.co/docs/accelerate/usage_guides/big_modeling) about `device_map="auto"`, they mentioned

> The model parallelism used when your model is split on several GPUs is naive and not optimized, meaning that only one GPU works at a given time and the other sits idle.

However, when the model fits in a single GPU, we want to use multiple GPUs to accelerate training by splitting the batch into multiple GPUs (data parallel). Is there a way to do that now?

Not sure if my attempt is correct: I tried to set `device_map` and `max_memory` to the default value when loading weights and use `accelerate launch --num_processes 2 qlora.py ...` to run the script on 2 GPUs, but I get a CUDA OOM error even for a batch size that is much smaller than the single GPU batch size. If I reduce the batch size by a lot, I get `RuntimeError: Expected to mark a variable ready only once.`

**Comment by fomalhautb** [comment]
I might have found the solution: same as above, set device_map and max_memory back to the default value, and then pass in `--ddp_find_unused_parameters False` to the `qlora.py` script. Then I can train with 100% GPU utilization of both GPUs. Also, the `per_device_train_batch_size` parameter seems to be "per device" now.

Please correct me if I am wrong

**Comment by g588928812** [comment]
just out of curiosity since i'm also trying to do the same, what did you set `per_device_train_batch_size` to? 

also related, why does `per_device_train_batch_size` * `gradient_accumulation_steps` have to be 16?

> Make sure to adjust per_device_train_batch_size and gradient_accumulation_steps so that their product is 16 and training fits on your GPUs.

**Comment by fomalhautb** [comment]
> just out of curiosity since i'm also trying to do the same, what did you set `per_device_train_batch_size` to?
> 
> also related, why does `per_device_train_batch_size` * `gradient_accumulation_steps` have to be 16?
> 
> > Make sure to adjust per_device_train_batch_size and gradient_accumulation_steps so that their product is 16 and training fits on your GPUs.

After my changes mentioned above, I think the actually global batch size is `per_device_train_batch_size` * `gradient_accumulation_steps` * `num_device`. So for my two GPUs setup, I set `per_device_train_batch_size` to 8 and `gradient_accumulation_steps` to 0.

For the second question, as I understand, they just want you to have the same batch size as their original model (which is 16) so you can reproduce the original results. If you want to tune your own model, you can change it for your need.

**Comment by AntoineBlanot** [comment]
Reopening this issue since for me `accelerate launch --num_processes 4 qlora.py --ddp_find_unused_parameters False ...` did not work with 4 GPUs. Do someone managed to make it work?

**Comment by giaosudau** [comment]
did the same accelerate launch --num_processes 4 qlora.py     --ddp_find_unused_parameters False 
but still got OOM

**Comment by geronimi73** [comment]
this script works for me to train on 5x3090 w/ accelerate: https://github.com/geronimi73/qlora-minimal/blob/main/qlora.py

**Comment by geronimi73** [comment]
> did the same accelerate launch --num_processes 4 qlora.py --ddp_find_unused_parameters False but still got OOM

lower the batch size?
