### ISSUE TITLE
Error invalid device ordinal at line 359 in file /mnt/c/Users/qwopq/Downloads/qlora/bitsandbytes/csrc/pythonInterface.c

### ISSUE THREAD

**Issue by qwopqwop200** [artidoro/qlora#3]
I am using cuda 11.8 and wsl2. LLaMA - 7B
I installed a new version of bitsandbytes to use the qlora, but it doesn't work.
```
(base) root@DESKTOP-DRKMHOU:/mnt/c/Users/qwopq/Downloads/qlora/qlora-main# bash scripts/finetune.sh

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /root/anaconda3/lib/python3.9/site-packages/bitsandbytes-0.39.0-py3.9.egg/bitsandbytes/libbitsandbytes_cuda117.so
CUDA SETUP: CUDA runtime path found: /root/anaconda3/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /root/anaconda3/lib/python3.9/site-packages/bitsandbytes-0.39.0-py3.9.egg/bitsandbytes/libbitsandbytes_cuda117.so...
loading base model ./llama-7b...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:22<00:00, 11.44s/it]
/root/anaconda3/lib/python3.9/site-packages/peft/utils/other.py:76: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(
adding LoRA modules...
trainable params: 79953920.0 || all params: 3660320768 || trainable: 2.184341894267557
loaded model
Using pad_token, but it is not set yet.
Found cached dataset parquet (/root/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 947.44it/s]
Loading cached processed dataset at /root/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-95a00d56074ae5fa.arrow
Splitting train dataset in train and validation according to `eval_dataset_size`
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-aedf12585a19bef4.arrow and /root/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-2ff9ed40565a4b8c.arrow
Loading cached processed dataset at /root/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-b83a3c430699603c.arrow
Loading cached processed dataset at /root/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-e983acc2d14f99d2.arrow
Found cached dataset json (/root/.cache/huggingface/datasets/json/default-e1a2135500543221/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1694.33it/s]
torch.float32 422326272 0.11537932153507864
torch.uint8 3238002688 0.8846206784649213
  0%|                                                                                                                                                    | 0/10000 [00:00<?, ?it/s]
Error invalid device ordinal at line 359 in file /mnt/c/Users/qwopq/Downloads/qlora/bitsandbytes/csrc/pythonInterface.c
```

**Comment by artidoro** [comment]
Hey! Thanks a lot for your interest in QLoRA. The necessary changes to use QLoRA will be merged in the transformers library tomorrow morning and we will update this repo with installation instructions.

**Comment by qwopqwop200** [comment]
> Hey! Thanks a lot for your interest in QLoRA. The necessary changes to use QLoRA will be merged in the transformers library tomorrow morning and we will update this repo with installation instructions.

I have already installed Transformer bnb PR.
But it doesn't work.

**Comment by diegomontoya** [comment]
@qwopqwop200  I am using Cuda 12.1 with  Driver Version: 530.41.03 and it works for me.

**Comment by qwopqwop200** [comment]
If so, I'm guessing it's a wsl issue.

**Comment by qwopqwop200** [comment]
https://github.com/TimDettmers/bitsandbytes/blob/main/csrc/pythonInterface.c#L359
Commenting out this code solved the problem.

**Comment by phalexo** [comment]
def prefetch_tensor(A, to_cpu=False):
    assert A.is_paged, 'Only paged tensors can be prefetched!'
    if to_cpu:
        deviceid = -1
    else:
        deviceid = A.page_deviceid

    num_bytes = dtype2bytes[A.dtype]*A.numel()
    lib.cprefetch(get_ptr(A), ct.c_size_t(num_bytes), ct.c_int32(deviceid))

The above function is part of bitsandbytes


Need to check if deviceid is -1 I took a brief look at python funcs and it seems that to_cpu=False in all the places I looked.

Also, is this cast ct.c_int32 correct? Should it be unsigned, or maybe "short"?
